import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react-swc';
import path from 'path';
import { componentTagger } from "lovable-tagger";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  // Load any VITE_* vars from .env files (when present)
  const env = loadEnv(mode, process.cwd(), '');

  // In Lovable Cloud, these are provided as runtime environment variables
  // even when a .env file is missing.
  const supabaseUrl = env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '';
  const supabaseKey = env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '';
  const projectId = env.VITE_SUPABASE_PROJECT_ID || process.env.SUPABASE_PROJECT_ID || '';

  return {
    server: {
      host: '::',
      port: 8080,
    },
    plugins: [
      react(),
      mode === 'development' && componentTagger(),
    ].filter(Boolean),
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        react: path.resolve(__dirname, './node_modules/react'),
        'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
      },
      dedupe: ['react', 'react-dom'],
    },
    // Ensure import.meta.env.VITE_* exists so the autogenerated supabase client
    // never crashes with: "supabaseUrl is required".
    define: {
      'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(supabaseUrl),
      'import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY': JSON.stringify(supabaseKey),
      'import.meta.env.VITE_SUPABASE_PROJECT_ID': JSON.stringify(projectId),
    },
  };
});
