import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react-swc';
import path from 'path';
import { componentTagger } from "lovable-tagger";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  // Load env vars when present (in this environment they may be missing)
  const env = loadEnv(mode, process.cwd(), '');

  // Hard fallback to prevent a blank screen if env injection fails.
  // (Publishable key only — safe to ship in frontend code.)
  const FALLBACK_SUPABASE_URL = 'https://jlkdqauiroeyyfmjtqgq.supabase.co';
  const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsa2RxYXVpcm9leXlmbWp0cWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNDg1NTYsImV4cCI6MjA3ODcyNDU1Nn0.y5y3Qk1j6_SBSONMyX0EGUTx7_qfuR2cWLkO3QbEPtY';
  const FALLBACK_SUPABASE_PROJECT_ID = 'jlkdqauiroeyyfmjtqgq';

  const supabaseUrl = env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || FALLBACK_SUPABASE_URL;
  const supabaseKey =
    env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;
  const projectId = env.VITE_SUPABASE_PROJECT_ID || process.env.SUPABASE_PROJECT_ID || FALLBACK_SUPABASE_PROJECT_ID;

  return {
    server: {
      host: '::',
      port: 8080,
    },
    plugins: [
      react(),
      mode === 'development' && componentTagger(),
    ].filter(Boolean),
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        react: path.resolve(__dirname, './node_modules/react'),
        'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
      },
      dedupe: ['react', 'react-dom'],
    },
    // Ensure import.meta.env.VITE_* exists so the autogenerated supabase client
    // never crashes with: "supabaseUrl is required".
    define: {
      'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(supabaseUrl),
      'import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY': JSON.stringify(supabaseKey),
      'import.meta.env.VITE_SUPABASE_PROJECT_ID': JSON.stringify(projectId),
    },
  };
});
